### PR TITLE
Fix NullReferenceException when returning an empty response from a Lua cloud script.

### PR DESCRIPTION
**Pull request by NickCaplinger**
Let me know if there are any issues with the PR. Thanks!

### CODE REVIEW

**Comment by mofirouz** [comment]
Hi Nick,

I've tried to replicate this issue but haven't been able to do so. Can you tell me more about the condition that this occurs under? It would be very helpful if you could provide a sample Cloud Code Lua code that you tested with.

Cheers,
Mo.

**Comment by NickCaplinger** [comment]
Hi Mo,

Sorry about that - I'll provide a sample when I get a chance.

Thanks,
Nick

**Comment by NickCaplinger** [comment]
Hi Mo, here is a simple test case that I was able to reproduce the issue with:

```lua
local M = {}

function M.test(context, payload)

   -- Notice the empty response
   local response = {}

   return context.result_json(response)
end

return M
```

The caveat to this is that I've been testing scripts from our cloud script editor tool that we built for our game. I haven't been able to get the GameUpTestScene to work despite updating the API key appropriately, as I continue to receive "401: API key is invalid".

**Comment by mofirouz** [comment]
Hi @NickCaplinger - The response coming back from the Cloud Code script is not an empty object, but rather a JSON Array. Currently the Unity SDK doesn't account for top-level JSON literals. I'll merge this code in now, and will also add a warning log output about this unsupported behaviour. Cheers.

**Comment by NickCaplinger** [comment]
Hi Mo, thanks for looking at this. I hope this was helpful!
Thanks.

**Pull request merged**
